name: network_media_mock_example
description: "Example app showcasing the features of the Network Media Mock package."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  network_media_mock: ^1.1.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true
