name: network_media_mock
description: "A package for mocking online media in Flutter widget and integration tests.
  Ideal for simulating network responses and serving local media assets without relying on live resources."
version: 1.0.0
homepage: https://hosseinzi.com
repository: https://github.com/hosseinzare1/network-media-mock

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
